env:
  global:
    - DATABASE_TEST=postgres://postgres@localhost:5432/epicmaildb

language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

before_script:
  - psql -c 'CREATE DATABASE epicmaildb;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
  - npm test

after_success:
  - npm run coveralls